name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build Docker image
      run: |
        docker build -t your-repo-name .
        docker tag your-repo-name:latest your-account-id.dkr.ecr.your-region.amazonaws.com/your-repo-name:latest

    - name: Push Docker image to ECR
      run: |
        docker push your-account-id.dkr.ecr.your-region.amazonaws.com/your-repo-name:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure kubectl
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
      run: |
        echo "${{ secrets.KUBECONFIG }}" > $KUBECONFIG
        kubectl config use-context arn:aws:eks:your-region:your-account-id:cluster/your-cluster-name

    - name: Deploy to EKS
      run: |
        kubectl set image deployment/your-deployment your-container=your-account-id.dkr.ecr.your-region.amazonaws.com/your-repo-name:latest
        kubectl rollout status deployment/your-deployment
